// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple2.Database
{

public enum EnemyType : byte
{
  Warrios = 0,
  Magician = 1,
  Pirate = 2,
  Thief = 3,
  Beginner = 4,
};


}
