// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple4.Database
{

public enum ECountry : byte
{
  NewYork = 1,
  VietNam = 2,
};


}
