// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple4.Database
{

public enum EFoodType : byte
{
  Donut = 1,
  ChocolateIcing = 2,
  MilkShake = 3,
  StrawberryIcing = 4,
  AlmondSlice = 5,
  Sprinkles = 6,
};


}
