// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple4.Database
{

public enum EProfitFoodType : byte
{
  TypeA = 1,
  TypeB = 2,
  TypeC = 3,
  TypeD = 4,
};


}
