// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple4.Database
{

public enum ERestaurant : byte
{
  Donut = 1,
  Burger = 2,
  Coffee = 3,
};


}
