// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple3.Database
{

public enum EColor : int
{
  Red = 0,
  Green = 1,
  Blue = 2,
};


}
