// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple3.Database
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Gun : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Gun GetRootAsGun(ByteBuffer _bb) { return GetRootAsGun(_bb, new Gun()); }
  public static Gun GetRootAsGun(ByteBuffer _bb, Gun obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Gun __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Damage { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateDamage(int Damage) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, Damage); return true; } else { return false; } }
  public int ReloadSpeed { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateReloadSpeed(int ReloadSpeed) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, ReloadSpeed); return true; } else { return false; } }

  public static Offset<FlatBufferGenerated.Simple3.Database.Gun> CreateGun(FlatBufferBuilder builder,
      int Damage = 0,
      int ReloadSpeed = 0) {
    builder.StartTable(2);
    Gun.AddReloadSpeed(builder, ReloadSpeed);
    Gun.AddDamage(builder, Damage);
    return Gun.EndGun(builder);
  }

  public static void StartGun(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDamage(FlatBufferBuilder builder, int Damage) { builder.AddInt(0, Damage, 0); }
  public static void AddReloadSpeed(FlatBufferBuilder builder, int ReloadSpeed) { builder.AddInt(1, ReloadSpeed, 0); }
  public static Offset<FlatBufferGenerated.Simple3.Database.Gun> EndGun(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBufferGenerated.Simple3.Database.Gun>(o);
  }
};


}
