// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferGenerated.Simple3.Database
{

public enum WeaponUnion : byte
{
  NONE = 0,
  Sword = 1,
  Gun = 2,
};


}
